Repository ClosedXML/ClosedXML, pull requests merged in 2018-05, with the labels that each got.

#839 Fix issues with copying worksheets across workbooks
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML/Excel/ConditionalFormats/IXLConditionalFormat.cs
  ClosedXML/Excel/ConditionalFormats/XLConditionalFormat.cs
  ClosedXML/Excel/Coordinates/XLAddress.cs
  ClosedXML/Excel/Drawings/IXLPicture.cs
  ClosedXML/Excel/Drawings/XLPicture.cs
  ClosedXML/Excel/NamedRanges/IXLNamedRange.cs
  ClosedXML/Excel/NamedRanges/XLNamedRange.cs
  ClosedXML/Excel/PageSetup/XLPageSetup.cs
  ClosedXML/Excel/Ranges/XLRangeAddress.cs
  ClosedXML/Excel/Ranges/XLRangeBase.cs
  ClosedXML/Excel/Rows/XLRow.cs
  ClosedXML/Excel/Tables/IXLTable.cs
  ClosedXML/Excel/Tables/XLTable.cs
  ClosedXML/Excel/XLWorksheet.cs
  ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatCopyTests.cs
  ClosedXML_Tests/Excel/ImageHandling/PictureTests.cs
  ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs
  ClosedXML_Tests/Excel/Saving/SavingTests.cs
  ClosedXML_Tests/Excel/Tables/TablesTests.cs
  ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
Labels: bug

#825 Get cell by full address
  ClosedXML/Excel/XLWorkbook.cs
  ClosedXML_Tests/Excel/Misc/XLWorkbookTests.cs
Labels: enhancement

#844 Correctly clear OpenXML cell value if ClosedXML cell value is empty
  ClosedXML/Excel/XLWorkbook_Save.cs
  ClosedXML_Tests/Excel/Clearing/ClearingTests.cs
Labels: bug

#857 Disallow negative row or column count to be inserted
  ClosedXML/Excel/Ranges/XLRangeBase.cs
  ClosedXML_Tests/Excel/Ranges/InsertingRangesTests.cs
  ClosedXML_Tests/Excel/Ranges/MergedRangesTests.cs
Labels: Breaking change, bug

#873 Bug fix - unsupported CellValues.String Data type
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML_Tests/Excel/Loading/LoadingTests.cs
  ClosedXML_Tests/Resource/Misc/CellWithStringDataType.xlsx
Labels: enhancement

#845 Update XLCell.MergedRange to use GetIntersectedRanges
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML/Excel/Ranges/IXLRanges.cs
  ClosedXML/Excel/Ranges/XLRanges.cs
  ClosedXML_Tests/Resource/Examples/Misc/DataValidation.xlsx
Labels: enhancement

#852 Invalidate named ranges when the worksheet is deleted
  ClosedXML/Excel/Coordinates/XLAddress.cs
  ClosedXML/Excel/NamedRanges/IXLNamedRange.cs
  ClosedXML/Excel/NamedRanges/IXLNamedRanges.cs
  ClosedXML/Excel/NamedRanges/XLNamedRange.cs
  ClosedXML/Excel/NamedRanges/XLNamedRanges.cs
  ClosedXML/Excel/Ranges/XLRangeAddress.cs
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML/Excel/XLWorksheet.cs
  ClosedXML_Tests/Excel/Coordinates/XLAddressTests.cs
  ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs
  ClosedXML_Tests/Excel/Ranges/XLRangeAddressTests.cs
  ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
Labels: enhancement

#888 Use current locale in the test instead of invariant culture
  ClosedXML_Tests/Excel/Cells/XLCellTests.cs
Labels: bug

#890 Upgrade System.Drawing.Common
  ClosedXML/ClosedXML.csproj
Labels: enhancement

#876 Correctly unprotect worksheet without password
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML_Tests/Excel/Worksheets/XLSheetProtectionTests.cs
  ClosedXML_Tests/Resource/Misc/SHA512PasswordProtection.xlsx
Labels: bug
