Repository ClosedXML/ClosedXML, pull requests merged in 2018-03, with the labels that each got.

#708 Correctly apply XLSortOrder sortOrder parameter for table sorting.
  ClosedXML/Excel/Ranges/XLRangeBase.cs
  ClosedXML/Excel/Ranges/XLRangeRow.cs
  ClosedXML/Excel/Tables/XLTable.cs
  ClosedXML_Examples/Ranges/Sorting.cs
  ClosedXML_Tests/Resource/Examples/Ranges/Sorting.xlsx
Labels: bug

#710 range copy fix for conditional formats
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML/Excel/ConditionalFormats/XLConditionalFormat.cs
  ClosedXML_Tests/ClosedXML_Tests.csproj
  ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatCopyTests.cs
Labels: bug

#721 FIX Shifting conditional format ranges works slow and incorrectly
  ClosedXML/Excel/Ranges/XLRangeBase.cs
  ClosedXML/Excel/XLWorksheet.cs
  ClosedXML_Tests/ClosedXML_Tests.csproj
  ClosedXML_Tests/Excel/ConditionalFormats/ConditionalFormatShiftTests.cs
  ClosedXML_Tests/Resource/Examples/Ranges/DeletingRanges.xlsx
Labels: enhancement

#718 Fix issues with data validation rules
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML/Excel/DataValidation/XLDataValidation.cs
  ClosedXML/Excel/DataValidation/XLDataValidations.cs
  ClosedXML/Excel/Ranges/XLRangeBase.cs
  ClosedXML/Excel/Ranges/XLRanges.cs
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs
  ClosedXML_Tests/Resource/Examples/Misc/DataValidation.xlsx
Labels: enhancement

#724 Improve determining if the cell is of type Table.Total
  ClosedXML/Excel/XLWorkbook_Save.cs
Labels: enhancement

#732 Fix COUNTBLANK for invalid ranges
  ClosedXML/Excel/CalcEngine/Expression.cs
  ClosedXML/Excel/CalcEngine/Functions/Statistical.cs
  ClosedXML_Tests/Excel/CalcEngine/StatisticalTests.cs
Labels: enhancement

#727 Refactor XLClearOptions and implement conditional formatting clearing
  ClosedXML/ClosedXML.csproj
  ClosedXML/Excel/Cells/IXLCell.cs
  ClosedXML/Excel/Cells/IXLCells.cs
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML/Excel/Cells/XLCells.cs
  ClosedXML/Excel/Columns/IXLColumn.cs
  ClosedXML/Excel/Columns/IXLColumns.cs
  ClosedXML/Excel/Columns/XLColumn.cs
  ClosedXML/Excel/Columns/XLColumns.cs
  ClosedXML/Excel/Ranges/IXLBaseCollection.cs
  ClosedXML/Excel/Ranges/IXLRange.cs
  ClosedXML/Excel/Ranges/IXLRangeBase.cs
  ClosedXML/Excel/Ranges/IXLRangeColumn.cs
  ClosedXML/Excel/Ranges/IXLRangeColumns.cs
  ClosedXML/Excel/Ranges/IXLRangeRow.cs
  ClosedXML/Excel/Ranges/IXLRangeRows.cs
  ClosedXML/Excel/Ranges/IXLRanges.cs
  ClosedXML/Excel/Ranges/XLRange.cs
  ClosedXML/Excel/Ranges/XLRangeBase.cs
  ClosedXML/Excel/Ranges/XLRangeColumn.cs
  ClosedXML/Excel/Ranges/XLRangeColumns.cs
  ClosedXML/Excel/Ranges/XLRangeRow.cs
  ClosedXML/Excel/Ranges/XLRangeRows.cs
  ClosedXML/Excel/Ranges/XLRanges.cs
  ClosedXML/Excel/Rows/IXLRow.cs
  ClosedXML/Excel/Rows/IXLRows.cs
  ClosedXML/Excel/Rows/XLRow.cs
  ClosedXML/Excel/Rows/XLRows.cs
  ClosedXML/Excel/Tables/IXLTable.cs
  ClosedXML/Excel/Tables/IXLTableRow.cs
  ClosedXML/Excel/Tables/IXLTableRows.cs
  ClosedXML/Excel/Tables/IXLTables.cs
  ClosedXML/Excel/Tables/XLTable.cs
  ClosedXML/Excel/Tables/XLTableRow.cs
  ClosedXML/Excel/Tables/XLTableRows.cs
  ClosedXML/Excel/Tables/XLTables.cs
  ClosedXML/Excel/XLClearOptions.cs
  ClosedXML_Examples/Ranges/AddingRowToTables.cs
  ClosedXML_Examples/Tables/UsingTables.cs
  ClosedXML_Tests/ClosedXML_Tests.csproj
  ClosedXML_Tests/Excel/Cells/XLCellTests.cs
  ClosedXML_Tests/Excel/Clearing/ClearingTests.cs
  ClosedXML_Tests/Excel/DataValidations/DataValidationTests.cs
  ClosedXML_Tests/Excel/Ranges/XLRangeBaseTests.cs
Labels: Breaking change, enhancement

#735 Fix expected order of SUMIFS parameters.
  ClosedXML/Excel/CalcEngine/CalcEngineHelpers.cs
  ClosedXML/Excel/CalcEngine/Functions/MathTrig.cs
  ClosedXML_Tests/Excel/CalcEngine/MathTrigTests.cs
Labels: bug

#739 Fix XLCFColorScaleConverter for indexed and theme colors
  ClosedXML/Excel/ConditionalFormats/Save/XLCFColorScaleConverter.cs
Labels: enhancement

#741 Treat negative row and column numbers as invalid
  ClosedXML/Excel/Columns/XLColumn.cs
  ClosedXML/Excel/Rows/XLRow.cs
  ClosedXML_Tests/Excel/Columns/ColumnTests.cs
  ClosedXML_Tests/Excel/Rows/RowTests.cs
Labels: bug

#742 Refactor IsInvalid to IsValid
  ClosedXML/Excel/Columns/XLColumn.cs
  ClosedXML/Excel/Ranges/IXLRangeAddress.cs
  ClosedXML/Excel/Ranges/XLRangeAddress.cs
  ClosedXML/Excel/Ranges/XLRangeBase.cs
  ClosedXML/Excel/Ranges/XLRanges.cs
  ClosedXML/Excel/Rows/XLRow.cs
  ClosedXML/Excel/XLWorksheet.cs
  ClosedXML/XLHelper.cs
  ClosedXML_Tests/Excel/AutoFilters/AutoFilterTests.cs
  ClosedXML_Tests/Excel/Columns/ColumnTests.cs
  ClosedXML_Tests/Excel/Ranges/InsertingRangesTests.cs
  ClosedXML_Tests/Excel/Rows/RowTests.cs
Labels: Breaking change, enhancement

#746 IsEvaluating flag added to XLCell
  ClosedXML/Excel/CalcEngine/XLCalcEngine.cs
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML_Tests/Excel/Cells/XLCellTests.cs
Labels: enhancement

#748 Add IXLCell.MergedRange()
  ClosedXML/Excel/Cells/IXLCell.cs
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML_Tests/Excel/Worksheets/XLWorksheetTests.cs
Labels: enhancement

#749 Exclude empty font, border and fill sections in differential styles
  ClosedXML/Excel/XLWorkbook_Save.cs
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFContains.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFDatesOccurring.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFEndsWith.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFEqualsNumber.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFEqualsString.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFIsBlank.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFIsError.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFMultipleConditions.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFNotBlank.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFNotContains.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFNotEqualsNumber.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFNotEqualsString.xlsx
  ClosedXML_Tests/Resource/Examples/ConditionalFormatting/CFNotError.xlsx
Labels: bug

#750 Implement IsEvaluating flag for simple/direct formula evaluation too.
  ClosedXML/Excel/Cells/XLCell.cs
  ClosedXML_Tests/Excel/Cells/XLCellTests.cs
Labels: enhancement

#756 Make XLPivotField internal
  ClosedXML/Excel/PivotTables/XLPivotField.cs
Labels: Breaking change, enhancement
