Repository ClosedXML/ClosedXML, pull requests merged in 2019-02, with the labels that each got.

#1135 Correctly load column-wide styles
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML_Tests/Excel/Styles/NumberFormatTests.cs
  ClosedXML_Tests/Resource/Examples/AutoFilter/DateTimeGroupAutoFilter.xlsx
  ClosedXML_Tests/Resource/Examples/Styles/StyleIncludeQuotePrefix.xlsx
Labels: bug

#1136 Implement NUMBERVALUE function
  ClosedXML/Excel/CalcEngine/Functions/Text.cs
  ClosedXML_Tests/Excel/CalcEngine/FunctionsTests.cs
  ClosedXML_Tests/Excel/CalcEngine/TextTests.cs
Labels: enhancement

#1134 Correctly propagate worksheet style to cells from a worksheet
  ClosedXML/Excel/XLWorksheet.cs
  ClosedXML_Tests/Excel/Styles/StyleTests.cs
Labels: .Report, bug

#1137 Fix changing inner borders of the range
  ClosedXML/Excel/Style/XLBorder.cs
  ClosedXML_Tests/Excel/Loading/LoadingTests.cs
  ClosedXML_Tests/Excel/Styles/BorderTests.cs
  ClosedXML_Tests/Resource/Other/StyleReferenceFiles/MergedCellsBorder/inputfile.xlsx
Labels: bug

#1133 Enumerate ranges in a deterministic order
  ClosedXML/Excel/ConditionalFormats/XLConditionalFormats.cs
  ClosedXML/Excel/Ranges/XLRanges.cs
  ClosedXML_Tests/Excel/NamedRanges/NamedRangesTests.cs
  ClosedXML_Tests/Excel/Ranges/MergedRangesTests.cs
  ClosedXML_Tests/Excel/Ranges/XLRangeBaseTests.cs
  ClosedXML_Tests/Resource/Examples/Misc/CopyingRowsAndColumns.xlsx
  ClosedXML_Tests/Resource/Examples/Ranges/SelectingRanges.xlsx
Labels: .Report, bug

#1150 Correctly clear inline string when required
  ClosedXML/Excel/XLWorkbook_Save.cs
  ClosedXML_Tests/Excel/Saving/SavingTests.cs
  ClosedXML_Tests/Resource/Other/InlineStrings/inputfile.xlsx
  ClosedXML_Tests/Resource/Other/InlineStrings/outputfile.xlsx
Labels: bug

#1151 Performance improvement to delete entire columns
  ClosedXML/Excel/XLWorkbook_Save.cs
Labels: enhancement

#1153 Correctly throw DivisionByZeroException when denominator is zero.
  ClosedXML/Excel/CalcEngine/Expression.cs
  ClosedXML_Tests/Excel/CalcEngine/CalcEngineExceptionTests.cs
Labels: bug
