Repository ClosedXML/ClosedXML, pull requests merged in 2019-04, with the labels that each got.

#1129 Alternative implementation of pivot table formats
  ClosedXML/Excel/EnumConverter.cs
  ClosedXML/Excel/PivotTables/IXLPivotField.cs
  ClosedXML/Excel/PivotTables/IXLPivotFields.cs
  ClosedXML/Excel/PivotTables/IXLPivotTable.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/AbstractPivotFieldReference.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotFieldStyleFormats.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotStyleFormat.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotStyleFormats.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotTableStyleFormats.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/IXLPivotValueStyleFormat.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/PivotLabelFieldReference.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/PivotValueFieldReference.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotFieldStyleFormats.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotStyleFormat.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotStyleFormatEnums.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotStyleFormats.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotTableStyleFormats.cs
  ClosedXML/Excel/PivotTables/PivotStyleFormats/XLPivotValueStyleFormat.cs
  ClosedXML/Excel/PivotTables/PivotValues/IXLPivotValues.cs
  ClosedXML/Excel/PivotTables/PivotValues/XLPivotValues.cs
  ClosedXML/Excel/PivotTables/XLPivotAreaValues.cs
  ClosedXML/Excel/PivotTables/XLPivotField.cs
  ClosedXML/Excel/PivotTables/XLPivotFields.cs
  ClosedXML/Excel/PivotTables/XLPivotTable.cs
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML/Excel/XLWorkbook_Save.cs
  ClosedXML_Tests/Excel/PivotTables/XLPivotTableTests.cs
Labels: enhancement

#1170 Remove IXLSheetProtection.IsProtected public setter
  ClosedXML/Excel/IXLSheetProtection.cs
Labels: Breaking change, enhancement

#1172 Clear all RelId's if workbook is loaded from template.
  ClosedXML/Excel/XLWorkbook.cs
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML_Tests/TestHelper.cs
Labels: bug

#1174 Correctly dispose temporary memorystream
  ClosedXML/Excel/XLWorkbook.cs
Labels: enhancement

#1183 Improve Merge operation performance
  ClosedXML/Excel/CalcEngine/CellRangeReference.cs
  ClosedXML/Excel/Ranges/XLRangeBase.cs
Labels: enhancement
