Repository ClosedXML/ClosedXML, pull requests merged in 2019-06, with the labels that each got.

#1224 Improve performance of loading workbooks having many merged ranges (#1220)
  ClosedXML/Excel/Ranges/XLRangeBase.cs
Labels: enhancement

#1196 Fix error by two pivot with one source #1195
  ClosedXML/Excel/XLWorkbook_Save.cs
  ClosedXML_Tests/Excel/PivotTables/XLPivotTableTests.cs
  ClosedXML_Tests/Resource/Examples/PivotTables/PivotTables.xlsx
  ClosedXML_Tests/Resource/Other/PivotTableReferenceFiles/PivotTableWithNoneTheme/outputfile.xlsx
  ClosedXML_Tests/Resource/Other/PivotTableReferenceFiles/TwoPivotTablesWithSingleSource/input.xlsx
  ClosedXML_Tests/Resource/Other/PivotTableReferenceFiles/TwoPivotTablesWithSingleSource/output.xlsx
Labels: bug

#1223 Fix pivot subtotals loading
  ClosedXML/Excel/XLWorkbook_Load.cs
  ClosedXML/Excel/XLWorkbook_Save.cs
  ClosedXML_Tests/Excel/PivotTables/XLPivotTableTests.cs
  ClosedXML_Tests/Resource/Other/PivotTableReferenceFiles/PivotSubtotalsSource/input.xlsx
  ClosedXML_Tests/Resource/Other/PivotTableReferenceFiles/TwoPivotTablesWithSingleSource/output.xlsx
Labels: .Report, bug
