Repository ClosedXML/ClosedXML, pull requests merged in 2020-04, with the labels that each got.

#1399 .CellsUsed() should return only cells with content.
  ClosedXML/Excel/Columns/XLColumn.cs
  ClosedXML/Excel/Rows/XLRow.cs
  ClosedXML/Excel/XLWorksheet.cs
  ClosedXML_Tests/Excel/Ranges/UsedAndUnusedCellsTests.cs
Labels: Regression

#1406 Prevent int overflow with working with large TimeSpan values
  ClosedXML/XLHelper.cs
  ClosedXML_Tests/Excel/Cells/XLCellTests.cs
Labels: Regression, bug

#1402 IEnumerator improvements - avoid evaluation of empty sheets
  ClosedXML/Excel/CalcEngine/CellRangeReference.cs
  ClosedXML/Excel/CalcEngine/Expression.cs
  ClosedXML_Tests/Excel/CalcEngine/CalcEngineCellEnumerationTests.cs
Labels: bug

#1400 Ensure auto-generated table name is unique across all worksheets
  ClosedXML/Excel/XLWorksheet.cs
  ClosedXML_Tests/Excel/Tables/TablesTests.cs
  ClosedXML_Tests/Resource/Examples/Misc/AddingDataSet.xlsx
Labels: bug
